# Generated by Django 5.1.4 on 2024-12-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('nationality', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('student_age', models.CharField(blank=True, max_length=10, null=True)),
                ('cgp', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
    ]
